add script and task to deploy it

diff --git a/tenant/rhem-virtual-machine/templates/configmap.yaml b/tenant/rhem-virtual-machine/templates/configmap.yaml
--- a/tenant/rhem-virtual-machine/templates/configmap.yaml
+++ b/tenant/rhem-virtual-machine/templates/configmap.yaml
@@ -68,3 +68,132 @@ data:
             group: {{ .username }}
             mode: '0640'
             {{- end }}
+        - name: Deploy import-disk-image script
+          ansible.builtin.copy:
+            src: "{{ "{{" }} playbook_dir {{ "}}" }}/import-disk-image.sh"
+            dest: /usr/local/bin/import-disk-image
+            owner: root
+            group: root
+            mode: '0755'
+
+  import-disk-image.sh: |
+    #!/usr/bin/env bash
+
+    set -euo pipefail
+
+    DELETE_FLAG="false"
+
+    usage() {
+      cat <<EOF
+    Usage: import-disk-image [--delete=true/false] [--qcow-path=/path/to/dir]
+
+    Options:
+      --delete=true/false  (bool)  If true, delete the existing DataVolume - this will trigger a re-import.
+      --qcow-path=<path>   Directory containing the qcow2 file to be imported, which should be named 'disk.qcow2'.
+      -h                   Show this help.
+
+    Examples:
+      import-disk-image --qcow-path=/home/user1/output
+      import-disk-image --delete=true --qcow-path=/home/user1/output
+    EOF
+    }
+
+    while [[ $# -gt 0 ]]; do
+      case "$1" in
+        --delete=*)
+          val="${1#*=}"
+          if [[ "$val" =~ ^(true|false)$ ]]; then
+            DELETE_FLAG="$val"
+          else
+            echo "ERROR: --delete must be true or false"
+            exit 1
+          fi
+          shift
+          ;;
+        --qcow2-path=*)
+          QCOW_PATH="${1#*=}"
+          shift
+          ;;
+        -h|--help)
+          usage
+          exit 1
+          ;;
+        *)
+          echo "Unknown argument: $1"
+          usage
+          exit 1
+          ;;
+      esac
+    done
+
+    if podman ps -a --format "{{.Names}}" | grep -q "^httpd-qcow2$"; then
+      echo "Existing container found, removing it..."
+      podman rm -f httpd-qcow2 > /dev/null
+    fi
+
+    if [[ -n "$QCOW_PATH" ]]; then
+      echo "Hosting qcow in path: $QCOW_PATH"
+
+      if [[ ! -d "$QCOW_PATH" ]]; then
+        echo "ERROR: qcow-path '$QCOW_PATH' is not a directory."
+        exit 1
+      fi
+
+      if podman ps -a --format "{{.Names}}" | grep -q "^httpd-qcow2$"; then
+        echo "Existing container found, removing it..."
+        podman rm -f httpd-qcow2 >/dev/null
+      fi
+
+      echo "Starting new container..."
+      podman run -d \
+        --name httpd-qcow2 \
+        -p 8888:8080 \
+        -v "$QCOW_PATH":/var/www/html:Z \
+        ubi9/httpd-24
+
+      echo "Container 'httpd-qcow2' running on port 8888"
+    fi
+
+    echo "Checking cluster login..."
+    if ! oc whoami >/dev/null 2>&1; then
+      echo "ERROR: You are not logged in to an OpenShift cluster."
+      echo "Ensure you are logged in before running this script."
+      echo "Copy the login command from the web console to login."
+      exit 1
+    else
+      echo "Logged in as $(oc whoami)..."
+    fi
+
+    echo "Ensuring the correct namespace is used..."
+    oc project wksp-{{ .Values.tenant }}
+
+    if [[ "$DELETE_FLAG" == "true" ]]; then
+      echo "Deleting existing DataVolume..."
+      oc delete DataVolume drone-virtual-machine --ignore-not-found=true
+      echo "Wait for deletion..."
+      sleep 10
+    fi
+
+    echo "Triggering DataVolume import..."
+    oc apply -f - <<EOF
+    ---
+    apiVersion: cdi.kubevirt.io/v1beta1
+    kind: DataVolume
+    metadata:
+      name: drone-virtual-machine
+      annotations:
+        "cdi.kubevirt.io/storage.bind.immediate.requested": "true"
+    spec:
+      pvc:
+        accessModes:
+          - ReadWriteOnce
+        resources:
+          requests:
+            storage: 30Gi
+        volumeMode: Block
+      source:
+        http:
+          url: http://import-disk-image.wksp-{{ .Values.tenant }}.svc.cluster.local:8888/disk.qcow2
+    EOF
+
+    echo "Done."
